spring:
  application:
    name: spring-boot-keycloak-sample5
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.keycloak.serverUrl}/realms/${app.keycloak.realm}
server:
  port: 8080
  servlet:
    context-path: /auth
app:
  keycloak:
    admin:
      clientId: admin-cli
      clientSecret: pHJbF76NVZA3gyynb0a5PzHIgZaF3bdJ
    realm: PowerRanger
    serverUrl: http://localhost:7080
